apiVersion: elastic.bobfintech.com/v1alpha1
kind: Elasticsearch
metadata:
  name: demo-elasticsearch
spec:
  size: 5
  image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
  jvm: "-Xms2g -Xmx2g"
  env:
    - name: CLUSTER_NAME
      value: "cao"
    - name: test
      value: "jiba"
#    - name: cluster.initial_master_nodes
#      value: demo-elasticsearch-0.demo-elasticsearch-headless-service.default.svc.cluster.local,demo-elasticsearch-1.demo-elasticsearch-headless-service.default.svc.cluster.local,demo-elasticsearch-2.demo-elasticsearch-headless-service.default.svc.cluster.local
#    - name: discovery.seed_hosts
#      value: demo-elasticsearch-headless-service
#      value: demo-elasticsearch-0.demo-elasticsearch-headless-service.default.svc.cluster.local,demo-elasticsearch-1.demo-elasticsearch-headless-service.default.svc.cluster.local,demo-elasticsearch-2.demo-elasticsearch-headless-service.default.svc.cluster.local
  resources:
    requests:
      memory: 1024Mi
      cpu: 500m
    limits:
      memory: 3072Mi
      cpu: 1000m
  service:
    spec:
      ports:
        - name: https
          port: 9200
          protocol: TCP
          targetPort: 9200
        - name: transport
          port: 9300
          protocol: TCP
          targetPort: 9300
      type: NodePort
  config:
    "xpack.security.enabled": "false"
  storageclass: nfs-storageclass-z
  storageresourcerequest: 10Gi
